package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/Mahesh-Kete/citadel/backend/internal/github"
)

// Where the Citadel composite action lives. The auto-injected workflow's
// `uses:` line resolves to this. Override via CITADEL_ACTION_REF if you
// forked the citadel monorepo into your own GitHub namespace.
//
// Format: <owner>/<repo>/<path-to-action>@<ref>
func citadelActionRef() string {
	if v := strings.TrimSpace(os.Getenv("CITADEL_ACTION_REF")); v != "" {
		return v
	}
	return "Mahesh-Kete/monorepo/action@main"
}

// Where the citadel-equipped self-hosted runner can reach the backend.
// Defaults to localhost:8080 because the action runs on the runner host and
// the backend container publishes 8080 on the host. Override via
// CITADEL_RUNNER_BACKEND_URL if your topology differs.
func citadelRunnerBackendURL() string {
	if v := strings.TrimSpace(os.Getenv("CITADEL_RUNNER_BACKEND_URL")); v != "" {
		return v
	}
	return "http://localhost:8080"
}

// workflowYAML returns the .github/workflows/citadel.yml content that the
// connect-repo flow auto-commits to the user's repo on first connection.
func workflowYAML() []byte {
	return []byte(fmt.Sprintf(`# Auto-generated by Citadel. Loads the runtime EDR agent on every CI run.
# Safe to edit — Citadel will never overwrite this file once it exists.
# Docs: https://github.com/Mahesh-Kete/citadel

name: citadel
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  citadel-monitor:
    runs-on: [self-hosted, linux, citadel-runner]
    steps:
      - uses: actions/checkout@v4

      - name: Citadel
        uses: %s
        with:
          mode: audit          # switch to "block" to fail builds on critical detections
          backend-url: %s
          image-tag: dev
          watch-path: ${{ github.workspace }}

      # ─────────────────────────────────────────────────────────────
      # Add your real build/test steps below. Anything they spawn (npm
      # install, pip install, make, tests, …) will be captured by the
      # eBPF agent and surfaced in the Citadel dashboard.
      # ─────────────────────────────────────────────────────────────
      - name: Smoke check (replace me)
        run: |
          citadel-step "smoke check"
          echo "Hello from a Citadel-instrumented job."
          uname -a
`, citadelActionRef(), citadelRunnerBackendURL()))
}

// connectedRepo is the JSON returned to clients. Token is NEVER sent back
// — only stored.
type connectedRepo struct {
	ID           int64      `json:"id"`
	Repository   string     `json:"repository"`
	Note         string     `json:"note,omitempty"`
	CreatedAt    time.Time  `json:"created_at"`
	LastPolledAt *time.Time `json:"last_polled_at,omitempty"`
	LastError    string     `json:"last_error,omitempty"`
}

type connectRepoRequest struct {
	Repository string `json:"repository"`      // owner/repo
	Token      string `json:"token,omitempty"` // optional PAT
	Note       string `json:"note,omitempty"`
}

// POST /api/repos/connect
//
// If a PAT is provided, validates it by calling /user, then inserts into
// connected_repos. Repos can also be connected without a PAT for manual
// public-key / runner workflows; those rows are not GitHub-polled.
func (a *API) handleConnectRepo(w http.ResponseWriter, r *http.Request) {
	var req connectRepoRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}
	req.Repository = strings.ToLower(strings.TrimSpace(req.Repository))
	req.Token = strings.TrimSpace(req.Token)

	if !validRepoFormat(req.Repository) {
		writeError(w, http.StatusBadRequest, "repository must be in owner/repo format")
		return
	}

	cli := github.New()
	authenticatedAs := "manual setup"
	tokenProvided := req.Token != ""
	if tokenProvided {
		ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
		defer cancel()
		user, err := cli.Whoami(ctx, req.Token)
		if err != nil {
			writeError(w, http.StatusBadRequest, "token invalid: "+err.Error())
			return
		}
		authenticatedAs = user.Login

		// Quick sanity check that the token can also see the repo.
		if _, err := cli.ListRecentRuns(ctx, req.Token, req.Repository, 1); err != nil {
			writeError(w, http.StatusBadRequest, fmt.Sprintf("cannot read %s with this token: %v", req.Repository, err))
			return
		}
	}

	// Upsert.
	_, err := a.DB.ExecContext(r.Context(), `
		INSERT INTO connected_repos (repository, token, note)
		VALUES (?, NULLIF(?, ''), NULLIF(?, ''))
		ON CONFLICT(repository) DO UPDATE SET
			token=excluded.token,
			note=COALESCE(NULLIF(excluded.note, ''), note),
			last_error=NULL`,
		req.Repository, req.Token, req.Note)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "store: "+err.Error())
		return
	}

	// Look up the row we just inserted to surface its id (and reuse it for
	// the runner-bootstrap URL below).
	var repoID int64
	_ = a.DB.QueryRowContext(r.Context(),
		`SELECT id FROM connected_repos WHERE repository = ?`, req.Repository).Scan(&repoID)

	// Auto-inject .github/workflows/citadel.yml. Best-effort: we don't fail
	// the connect on this; the user can still add the workflow manually if
	// the PAT lacks write scope or anything else goes sideways.
	resp := map[string]any{
		"repository":       req.Repository,
		"authenticated_as": authenticatedAs,
		"token_provided":   tokenProvided,
	}
	if repoID > 0 {
		resp["repo_id"] = repoID
		if tokenProvided {
			resp["runner_bootstrap_url"] = fmt.Sprintf("/api/repos/%d/runner-bootstrap.sh", repoID)
		}
	}
	if !tokenProvided {
		resp["workflow_injected"] = false
		resp["workflow_message"] = "No PAT provided; add the workflow and runner manually."
	} else {
		injCtx, injCancel := context.WithTimeout(r.Context(), 15*time.Second)
		defer injCancel()
		put, putErr := cli.PutWorkflowFile(
			injCtx, req.Token, req.Repository,
			".github/workflows/citadel.yml",
			workflowYAML(),
			"Enable Citadel runtime EDR monitoring",
		)
		switch {
		case putErr != nil:
			a.Logger.Warn("workflow inject failed", "repo", req.Repository, "err", putErr)
			resp["workflow_injected"] = false
			resp["workflow_message"] = "Could not push .github/workflows/citadel.yml automatically: " +
				putErr.Error() + ". You can add it manually."
		case put.Skipped:
			resp["workflow_injected"] = false
			resp["workflow_message"] = put.Message
		default:
			resp["workflow_injected"] = true
			resp["workflow_message"] = put.Message
			resp["workflow_url"] = put.HTMLURL
		}
	}

	a.Logger.Info("repo connected",
		"repo", req.Repository,
		"as_user", authenticatedAs,
		"workflow_injected", resp["workflow_injected"])
	writeJSON(w, http.StatusOK, resp)
}

// GET /api/repos
func (a *API) handleListRepos(w http.ResponseWriter, r *http.Request) {
	rows, err := a.DB.QueryContext(r.Context(), `
		SELECT id, repository, COALESCE(note, ''), created_at, last_polled_at, COALESCE(last_error, '')
		FROM connected_repos
		ORDER BY created_at DESC`)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query: "+err.Error())
		return
	}
	defer func() { _ = rows.Close() }()

	out := make([]connectedRepo, 0)
	for rows.Next() {
		var c connectedRepo
		var lastPolledAt sql.NullTime
		if err := rows.Scan(&c.ID, &c.Repository, &c.Note, &c.CreatedAt, &lastPolledAt, &c.LastError); err != nil {
			writeError(w, http.StatusInternalServerError, "scan: "+err.Error())
			return
		}
		if lastPolledAt.Valid {
			t := lastPolledAt.Time
			c.LastPolledAt = &t
		}
		out = append(out, c)
	}
	writeJSON(w, http.StatusOK, out)
}

// DELETE /api/repos/{id}
//
// Cascades: removes events, detections, and runs belonging to the repo
// before deleting the connected_repos row itself. Wrapped in a transaction
// so a partial failure leaves nothing dangling.
func (a *API) handleDeleteRepo(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	// Resolve repo name first so we can scope the cascade.
	var repo string
	err := a.DB.QueryRowContext(r.Context(),
		`SELECT repository FROM connected_repos WHERE id = ?`, id).Scan(&repo)
	if errors.Is(err, sql.ErrNoRows) {
		writeError(w, http.StatusNotFound, "repo not found")
		return
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query: "+err.Error())
		return
	}

	tx, err := a.DB.BeginTx(r.Context(), nil)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "begin tx: "+err.Error())
		return
	}
	defer func() { _ = tx.Rollback() }()

	// Cascade in dependency order: events + detections reference run_id, runs
	// reference repository. Use a sub-select rather than a join-delete because
	// SQLite's syntax for DELETE-JOIN is awkward.
	delActionLogs, err := tx.ExecContext(r.Context(),
		`DELETE FROM github_action_logs WHERE run_id IN (SELECT id FROM runs WHERE repository = ?)`, repo)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "delete action logs: "+err.Error())
		return
	}
	delEvents, err := tx.ExecContext(r.Context(),
		`DELETE FROM events WHERE run_id IN (SELECT id FROM runs WHERE repository = ?)`, repo)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "delete events: "+err.Error())
		return
	}
	delDetections, err := tx.ExecContext(r.Context(),
		`DELETE FROM detections WHERE run_id IN (SELECT id FROM runs WHERE repository = ?)`, repo)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "delete detections: "+err.Error())
		return
	}
	delRuns, err := tx.ExecContext(r.Context(),
		`DELETE FROM runs WHERE repository = ?`, repo)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "delete runs: "+err.Error())
		return
	}
	delRepo, err := tx.ExecContext(r.Context(),
		`DELETE FROM connected_repos WHERE id = ?`, id)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "delete repo: "+err.Error())
		return
	}
	if err := tx.Commit(); err != nil {
		writeError(w, http.StatusInternalServerError, "commit: "+err.Error())
		return
	}

	evN, _ := delEvents.RowsAffected()
	dtN, _ := delDetections.RowsAffected()
	rnN, _ := delRuns.RowsAffected()
	rpN, _ := delRepo.RowsAffected()
	alN, _ := delActionLogs.RowsAffected()

	a.Logger.Info("repo disconnected (cascade)",
		"repo", repo,
		"runs", rnN, "events", evN, "detections", dtN, "action_logs", alN)

	writeJSON(w, http.StatusOK, map[string]int64{
		"deleted":             rpN,
		"runs_deleted":        rnN,
		"events_deleted":      evN,
		"detections_deleted":  dtN,
		"action_logs_deleted": alN,
	})
}

// POST /api/repos/{id}/refresh — triggers an immediate poll of the given
// repo by setting last_polled_at far in the past. The background poller
// picks it up within ~1 sweep.
func (a *API) handleRefreshRepo(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	// Find the repo, then trigger an immediate sync inline so the user
	// gets feedback right away.
	var repo string
	var token sql.NullString
	err := a.DB.QueryRowContext(r.Context(),
		`SELECT repository, token FROM connected_repos WHERE id = ?`, id).Scan(&repo, &token)
	if errors.Is(err, sql.ErrNoRows) {
		writeError(w, http.StatusNotFound, "repo not found")
		return
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query: "+err.Error())
		return
	}
	ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
	defer cancel()
	cli := github.New()
	tokenValue := ""
	if token.Valid {
		tokenValue = token.String
	}
	runs, err := cli.ListRecentRuns(ctx, tokenValue, repo, 20)
	if err != nil {
		writeError(w, http.StatusBadGateway, "github: "+err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]int{"fetched": len(runs)})
}

func validRepoFormat(repo string) bool {
	parts := strings.Split(repo, "/")
	if len(parts) != 2 {
		return false
	}
	return parts[0] != "" && parts[1] != ""
}

// GET /api/repos/{id}/runner-bootstrap.sh
//
// Returns a self-contained shell script for the user to paste into their
// runner VM. It mints a fresh registration token using the stored PAT,
// downloads the GitHub Actions runner (idempotent), registers it with label
// `citadel-runner`, and installs it as a systemd service.
//
// We return a script instead of "do it for me" because the backend runs in
// a container with no shell access to the host. One paste in the VM is the
// minimum the runner setup can be boiled down to.
func (a *API) handleRunnerBootstrap(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	var repo string
	var token sql.NullString
	err := a.DB.QueryRowContext(r.Context(),
		`SELECT repository, token FROM connected_repos WHERE id = ?`, id).Scan(&repo, &token)
	if errors.Is(err, sql.ErrNoRows) {
		writeError(w, http.StatusNotFound, "repo not found")
		return
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "query: "+err.Error())
		return
	}
	if !token.Valid || strings.TrimSpace(token.String) == "" {
		writeError(w, http.StatusBadRequest, "repo has no PAT; runner bootstrap requires a GitHub registration token")
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 15*time.Second)
	defer cancel()
	cli := github.New()
	rt, err := cli.RegistrationToken(ctx, token.String, repo)
	if err != nil {
		writeError(w, http.StatusBadGateway, "github registration-token: "+err.Error())
		return
	}

	script := renderRunnerBootstrap(repo, rt.Token)
	w.Header().Set("Content-Type", "text/x-shellscript; charset=utf-8")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`inline; filename="citadel-runner-%s.sh"`,
		strings.ReplaceAll(repo, "/", "_")))
	_, _ = w.Write([]byte(script))
}

// renderRunnerBootstrap returns a shell script the user can pipe straight
// into `bash`. The script is idempotent — running it twice does the right
// thing (re-registers with a fresh token, doesn't re-download the binary).
func renderRunnerBootstrap(repo, regToken string) string {
	const runnerVersion = "2.319.1"
	return fmt.Sprintf(`#!/usr/bin/env bash
# Citadel — self-hosted GitHub Actions runner bootstrap
#
# Generated for repo: %s
# Token valid: 1 hour
#
# Safe to re-run: existing install is re-registered with a fresh token
# rather than reinstalled from scratch.

set -euo pipefail

REPO=%q
TOKEN=%q
LABELS="self-hosted,linux,citadel-runner"
NAME="citadel-$(hostname)"
RUNNER_DIR="$HOME/actions-runner"
RUNNER_VERSION=%q

# 1. Detect arch and pick the right tarball.
case "$(uname -m)" in
  x86_64)  ARCH=x64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  *) echo "unsupported arch: $(uname -m)"; exit 1 ;;
esac

# 2. Install or refresh the runner under ~/actions-runner.
if [ ! -x "$RUNNER_DIR/config.sh" ]; then
  echo "==> Downloading actions-runner v$RUNNER_VERSION ($ARCH)"
  mkdir -p "$RUNNER_DIR"
  cd "$RUNNER_DIR"
  curl -fsSL -o runner.tar.gz \
    "https://github.com/actions/runner/releases/download/v$RUNNER_VERSION/actions-runner-linux-$ARCH-$RUNNER_VERSION.tar.gz"
  tar xzf runner.tar.gz
  rm -f runner.tar.gz
else
  echo "==> Runner already installed at $RUNNER_DIR"
  cd "$RUNNER_DIR"
fi

# 3. If a previous registration exists, tear it down completely.
#    config.sh-remove only works with a removal token from the OLD repo,
#    so for cross-repo switches we just delete the config files. The binary
#    layout (run.sh, svc.sh, externals/, ...) stays put so the next config.sh
#    succeeds without redownloading.
if [ -f .runner ]; then
  echo "==> Removing previous runner registration"
  if [ -x ./svc.sh ] && command -v sudo >/dev/null 2>&1; then
    sudo ./svc.sh stop      2>/dev/null || true
    sudo ./svc.sh uninstall 2>/dev/null || true
  fi
  ./config.sh remove --token "$TOKEN" >/dev/null 2>&1 || true
  rm -f .runner .credentials .credentials_rsaparams
fi

# 4. Register non-interactively with the citadel-runner label.
echo "==> Registering with GitHub for $REPO"
./config.sh \
  --url "https://github.com/$REPO" \
  --token "$TOKEN" \
  --name "$NAME" \
  --labels "$LABELS" \
  --work _work \
  --unattended \
  --replace

# 5. Install systemd unit so the runner survives reboots.
if command -v sudo >/dev/null 2>&1 && [ -x ./svc.sh ]; then
  echo "==> Installing systemd service"
  sudo ./svc.sh install
  sudo ./svc.sh start
  echo "==> Done. Service status:"
  sudo ./svc.sh status || true
else
  echo "==> svc.sh not available or no sudo; starting runner in this terminal."
  echo "    Press Ctrl-C to stop; runner will not auto-restart."
  ./run.sh
fi
`, repo, repo, regToken, runnerVersion)
}
